// <auto-generated />
namespace PayRentAndUse_V3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedBooking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedBooking));
        
        string IMigrationMetadata.Id
        {
            get { return "202103100518532_updatedBooking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
