// <auto-generated />
namespace PayRentAndUse_V3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class userroleupdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userroleupdated));
        
        string IMigrationMetadata.Id
        {
            get { return "202103070620150_userroleupdated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
