// <auto-generated />
namespace PayRentAndUse_V3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class validationAddedForVendor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validationAddedForVendor));
        
        string IMigrationMetadata.Id
        {
            get { return "202103021716211_validationAddedForVendor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
